theme: minima
title: My First GitHub Pages Website
author: Allen McCracken (Allen-Atom)
description: This is my first ever GitHub Pages website. GitHub Pages builds the site using the static site generator Jekyll.
